# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

  [[main]]
  name = "About"
  pageRef = "about"
  weight = 5

[[main]]
  name = "AoPS"
  weight = 20

[[main]]
  name = "Preálgebra"
  parent = "AoPS"
  #pageRef = "https://youtube.com"
  url = "https://youtube.com"
  weight = 20

[[main]]
  name = "Álgebra 1"
  parent = "AoPS"
  #pageRef = ""
  url = "https://youtube.com"
  weight = 30

#[[main]]
#  name = "Conteo y Probabilidad 1"
#  parent = "El País de los Números"
#  pageRef = ""
#  url = "https://youtube.com"
#  weight = 35

#[[main]]
#  name = "Introducción a la Geometría"
#  parent = "El País de los Números"
#  #pageRef = ""
#  url = "https://youtube.com"
#  weight = 40

#[[main]]
#  name = "Teoría Numérica"
#  parent = "El País de los Números"
#  #pageRef = ""
#  url = "https://youtube.com"
#  weight = 50

#[[main]]
#  name = "Álgebra 2"
#  parent = "El País de los Números"
#  #pageRef = ""
#  url = "https://youtube.com"
#  weight = 60

#[[main]]
#  name = "Conteo y Probabilidad 2"
#  parent = "El País de los Números"
#  #pageRef = ""
#  url = "https://youtube.com"
#  weight = 70

#[[main]]
#  name = "Precálculo"
#  parent = "El País de los Números"
#  #pageRef = ""
#  url = "https://youtube.com"
#  weight = 80

#[[main]]
#  name = "Cálculo"
#  parent = "El País de los Números"
#  #pageRef = ""
#  url = "https://youtube.com"
#  weight = 90

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

[[main]]
  name = "Music"
  pageRef = "music"
  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 #[[footer]]
 # name = "Tags"
 # pageRef = "tags"
 # weight = 10

 #[[footer]]
 #  name = "Categories"
 #  pageRef = "categories"
 #  weight = 20
